---
language: ruby
os:
  - linux
  - osx
dist: focal
compiler:
  - clang
  - gcc
cache: bundler
rvm:
  - 3.1.0
  - 3.0.2
  - 2.7.6
addons:
  apt:
    update: true
    packages:
      - cmake
      - doxygen
  homebrew:
    packages:
    - opencc
before_install:
  - gem install bundler -v 2.1.4
install:
    - ./.travis/install.sh 
    - bundle install
script: bundle exec rake